services:
  node:
    image: node-pnpm
    container_name: bot-service-app
    command: tail -f /dev/null
    working_dir: /code/services/bot-service
    volumes:
      - ../..:/code
    env_file:
      - ../../.env
      - ./.env
    networks:
      - ifrondonia-bot-net

networks:
  ifrondonia-bot-net:
    external: true